<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BLRLAP653" ignored="0" name="test failed Test" tests="10" failures="2" timestamp="11 May 2018 11:56:52 GMT" time="18.083" errors="0">
  <testcase name="test1" time="0.015" classname="RunFailedTestPractise.SampleTest"/>
  <testcase name="test2" time="0.006" classname="RunFailedTestPractise.SampleTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="RunFailedTestPractise.SampleTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="RunFailedTestPractise.SampleTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="RunFailedTestPractise.SampleTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at RunFailedTestPractise.SampleTest.test2(SampleTest.java:19)
	at Listners_RuntestDynamically.Runner1.main(Runner1.java:17)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="RunFailedTestPractise.SampleTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="RunFailedTestPractise.SampleTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="RunFailedTestPractise.SampleTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="RunFailedTestPractise.SampleTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at RunFailedTestPractise.SampleTest.test3(SampleTest.java:25)
	at Listners_RuntestDynamically.Runner1.main(Runner1.java:17)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.0" classname="RunFailedTestPractise.SampleTest"/>
</testsuite> <!-- test failed Test -->
